const coinTypeOptions = [
  { label: "BTC - BTC", value: "BTC" },
  { label: "BTC - BCH", value: "BCH" },
  { label: "BTC - BSV", value: "BSV" },
  { label: "BTC - LTC", value: "LTC" },
  { label: "BTC - Doge", value: "DOGE" },
  { label: "BTC - TBTC", value: "TBTC" },
  { label: "BTC - Omni USDT", value: "OMNI-USDT" },

  { label: "ETH - ETH", value: "ETH" },
  { label: "ETH - Arbitrum One", value: "A1" },
  { label: "ETH - Arbitrum Nova", value: "NOVA" },
  { label: "ETH - Avalance C", value: "AVAX" },
  { label: "ETH - Boba", value: "BOBA" },
  { label: "ETH - BNB Chain", value: "BSC" },
  { label: "ETH - Core", value: "CORE" },
  { label: "ETH - Cronos (EVM)", value: "CRO (ERC20)" },
  { label: "ETH - Celo", value: "CELO" },
  { label: "ETH - Conflux (EVM)", value: "CFX" },
  { label: "ETH - Endurance", value: "ACE" },
  { label: "ETH - Ethereum PoW", value: "ETHW" },
  { label: "ETH - Ethereum Fair", value: "ETHF" },
  { label: "ETH - Filecoin (EVM)", value: "FIL (ERC20)" },
  { label: "ETH - Fantom", value: "FTM" },
  { label: "ETH - Flare", value: "FLR" },
  { label: "ETH - Gnosis", value: "GNO" },
  { label: "ETH - Goerli", value: "GETH" },
  { label: "ETH - HAQQ Network", value: "HAQQ" },
  { label: "ETH - Klaytn", value: "KLAY" },
  { label: "ETH - KCC", value: "KCS" },
  { label: "ETH - Kava (EVM)", value: "KAVA (ERC20)" },
  { label: "ETH - Linea", value: "TBA" },
  { label: "ETH - Metis", value: "METIS" },
  { label: "ETH - Moonebeam", value: "GLMR" },
  { label: "ETH - Moonriver", value: "MOVR" },
  { label: "ETH - Mantle", value: "MNT" },
  { label: "ETH - Omega Network", value: "OMN" },
  { label: "ETH - OKTC", value: "OKT" },
  { label: "ETH - Optimism", value: "OP" },
  { label: "ETH - opBNB", value: "OPBNB" },
  { label: "ETH - Polygon", value: "MATIC" },
  { label: "ETH - Polygon zkEVM", value: "MATIC (zkEVM)" },
  { label: "ETH - Pulse Chain", value: "PULSE" },
  { label: "ETH - Sepolia", value: "SEPOLIA" },
  { label: "ETH - zkSync Era", value: "ZKSYNC-ERA" },
  { label: "ETH - Zeta Chain", value: "ZETA" },

  { label: "COSMOS - Atom", value: "ATOM" },
  { label: "COSMOS - Axelar", value: "AXL" },
  { label: "COSMOS - Cronos", value: "CRO" },
  { label: "COSMOS - Osmosis", value: "OSMO" },
  { label: "COSMOS - Evmos", value: "EVMOS" },
  { label: "COSMOS - Iris", value: "IRIS" },
  { label: "COSMOS - Juno", value: "JUNO" },
  { label: "COSMOS - Kava", value: "KAVA" },
  { label: "COSMOS - Kujira", value: "KUJI" },
  { label: "COSMOS - Secret", value: "SCRT" },
  { label: "COSMOS - Sei", value: "SEI" },
  { label: "COSMOS - Stargaze", value: "STARS" },
  { label: "COSMOS - Terra", value: "LUNA" },

  { label: "APTOS - Aptos", value: "APTOS" },
  { label: "EOS - EOS", value: "EOS" },
  { label: "SOL - Solana", value: "SOL" },
  { label: "STX - Stacks", value: "STX" },
  { label: "STARK - Starknet", value: "STARK" },
  { label: "SUI - SUI", value: "SUI" },
  { label: "TRX - Tron", value: "TRX" },
  { label: "ZKSPACE - Zkspace", value: "ZKSPACE" },
  { label: "ZKSYNC - Zkspace", value: "ZKSYNC" },
];

export { coinTypeOptions };
